# Generated by Django 5.2.15 on 2026-06-20 09:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import quiz.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="URL-safe identifier (e.g. 'ssc')", unique=True, validators=[django.core.validators.RegexValidator(message='Slug must be lowercase alphanumeric and hyphens only', regex='^[a-z0-9-]+$')])),
                ('name', models.CharField(help_text="Display name (e.g. 'SSC')", max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='school', help_text='Material Symbol name', max_length=50)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower = first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show on frontend?')),
                ('icon_color', models.CharField(default='blue', help_text="Tailwind color name (e.g. 'blue', 'purple')", max_length=20)),
                ('bg_color', models.CharField(default='bg-blue-100', help_text='Tailwind background class', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('unread', 'Unread'), ('read', 'Read')], default='unread', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Exam title', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('ai_summary', models.TextField(blank=True, help_text='Markdown formatted AI summary', null=True)),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated from subcategory + year + shift. Override only if needed.', max_length=250, unique=True)),
                ('year', models.IntegerField(blank=True, help_text='Exam year (e.g., 2024)', null=True)),
                ('shift', models.CharField(blank=True, help_text="e.g., 'Shift 1', 'Morning', 'Afternoon'", max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', help_text='Draft exams are not visible to students', max_length=20)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('duration_minutes', models.IntegerField(default=60)),
                ('total_questions', models.IntegerField(default=10)),
                ('marks_per_question', models.DecimalField(blank=True, decimal_places=2, help_text='Marks awarded for each correct answer', max_digits=5, null=True)),
                ('negative_marks', models.DecimalField(decimal_places=2, default=0.0, help_text='Marks deducted for each wrong answer', max_digits=5)),
                ('total_marks', models.IntegerField(blank=True, help_text='Total marks for this exam', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive exams are hidden from students')),
                ('supported_languages', models.JSONField(default=quiz.models.get_default_languages, help_text='Supported languages for this exam')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResourceTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True, validators=[django.core.validators.RegexValidator(message='Slug must be lowercase alphanumeric and hyphens only', regex='^[a-z0-9-]+$')])),
                ('color', models.CharField(default='gray', help_text="Tailwind color name e.g. 'blue', 'green', 'purple'", max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CurrentAffair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=600, unique=True, validators=[django.core.validators.RegexValidator(message='Slug must be lowercase alphanumeric and hyphens only', regex='^[a-z0-9-]+$')])),
                ('content', models.TextField(help_text='Full summarized content from AI')),
                ('summary', models.TextField(blank=True, help_text='Short 2-sentence summary for list view')),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('source_name', models.CharField(blank=True, max_length=200)),
                ('source_url', models.URLField(blank=True, max_length=1000)),
                ('published_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.category')),
            ],
            options={
                'verbose_name_plural': 'Current Affairs',
                'ordering': ['-published_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamRoadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g. 'Complete Syllabus for SSC CGL'", max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bookmarks', models.ManyToManyField(blank=True, related_name='bookmarked_roadmaps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_blocks', models.JSONField(blank=True, default=list, help_text='Blocks of content for the passage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passages', to='quiz.exam')),
            ],
        ),
        migrations.CreateModel(
            name='PracticeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('total_questions', models.IntegerField()),
                ('correct_answers', models.IntegerField()),
                ('accuracy', models.FloatField()),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('duration', models.IntegerField(blank=True, default=0, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('current_question_index', models.IntegerField(default=0)),
                ('is_paused', models.BooleanField(default=False)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_sessions', to='quiz.exam')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practice_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('mcq_single', 'Single Correct MCQ'), ('mcq_multiple', 'Multiple Correct MCQ'), ('numerical', 'Numerical Answer'), ('match_the_following', 'Match the Following')], default='mcq_single', max_length=20)),
                ('content_blocks', models.JSONField(default=list, help_text="List of content blocks [{type: 'text', value: '...'}, ...]")),
                ('options_blocks', models.JSONField(blank=True, default=list, help_text="List of options [{id: 'A', content: [...]}, ...]")),
                ('answer_metadata', models.JSONField(default=dict, help_text='Contains correct_options, numerical_range, partial_marking_enabled')),
                ('explanation_blocks', models.JSONField(blank=True, default=list, help_text='Legacy explanation blocks')),
                ('ai_tutor_data', models.JSONField(blank=True, default=dict, help_text='Contains hints and solution_steps')),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('topic', models.CharField(blank=True, max_length=100, null=True)),
                ('subtopic', models.CharField(blank=True, max_length=100, null=True)),
                ('difficulty_score', models.FloatField(blank=True, help_text='Continuous score (0.0 to 1.0)', null=True)),
                ('difficulty_label', models.CharField(blank=True, help_text='e.g. Medium', max_length=20, null=True)),
                ('cognitive_level', models.CharField(blank=True, help_text='e.g. apply, analyze', max_length=50, null=True)),
                ('order', models.IntegerField(default=0)),
                ('marks', models.IntegerField(default=1)),
                ('quality_score', models.FloatField(blank=True, null=True)),
                ('duplicate_hash', models.CharField(blank=True, db_index=True, max_length=256, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('translation_group_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('language', models.CharField(default='en', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.exam')),
                ('passage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='quiz.passage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CorrectionSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('question_text', 'Question Text'), ('correct_answer', 'Correct Answer'), ('option_text', 'Option Text')], max_length=20)),
                ('suggestion_data', models.JSONField()),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('upvotes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='quiz.question')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionPaperUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('exam_date', models.DateField()),
                ('file', models.FileField(upload_to='question_papers/')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('processed', 'Processed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.category')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoadmapPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g. 'Phase 1: Basic Numeracy'", max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0, help_text='Order in the timeline')),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='quiz.examroadmap')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RoadmapTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g. 'Percentage Basics'", max_length=200)),
                ('slug', models.SlugField(blank=True, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Slug must be lowercase alphanumeric and hyphens only', regex='^[a-z0-9-]+$')])),
                ('description', models.TextField(blank=True)),
                ('estimated_minutes', models.IntegerField(default=60, help_text='Estimated study time in minutes')),
                ('order', models.IntegerField(default=0)),
                ('resources', models.JSONField(blank=True, default=list, help_text="List of resources e.g. [{'type': 'video', 'url': '...', 'title': '...'}]")),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='quiz.roadmapphase')),
                ('prerequisites', models.ManyToManyField(blank=True, help_text='Prerequisites required before studying this topic', related_name='dependent_topics', to='quiz.roadmaptopic')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="URL-safe identifier (e.g. 'ssc-cgl')", unique=True, validators=[django.core.validators.RegexValidator(message='Slug must be lowercase alphanumeric and hyphens only', regex='^[a-z0-9-]+$')])),
                ('name', models.CharField(help_text="Display name (e.g. 'SSC CGL')", max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='school', help_text='Material Symbol name', max_length=50)),
                ('order', models.IntegerField(default=0, help_text='Display order within category')),
                ('is_active', models.BooleanField(default=True, help_text='Show on frontend?')),
                ('syllabus_pdf', models.FileField(blank=True, help_text='Syllabus PDF file for automated roadmap generation', null=True, upload_to='syllabus_pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='quiz.category')),
            ],
            options={
                'verbose_name_plural': 'SubCategories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='examroadmap',
            name='subcategory',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap', to='quiz.subcategory'),
        ),
        migrations.AddField(
            model_name='exam',
            name='subcategory',
            field=models.ForeignKey(blank=True, help_text='Select the subcategory this exam belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='quiz.subcategory'),
        ),
        migrations.CreateModel(
            name='TopicResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated from title', max_length=550, unique=True, validators=[django.core.validators.RegexValidator(message='Slug must be lowercase alphanumeric and hyphens only', regex='^[a-z0-9-]+$')])),
                ('short_description', models.TextField(blank=True, help_text='One-line summary shown in resource cards')),
                ('resource_type', models.CharField(choices=[('article', 'Article'), ('markdown_note', 'Markdown Note'), ('html_note', 'HTML Note'), ('latex_note', 'LaTeX Note'), ('video', 'Video'), ('pdf', 'PDF'), ('external_link', 'External Link'), ('ai_note', 'AI Note'), ('formula_sheet', 'Formula Sheet'), ('quiz', 'Quiz / Practice Set')], db_index=True, default='article', help_text='What kind of content is this?', max_length=30)),
                ('content_format', models.CharField(choices=[('markdown', 'Markdown'), ('html', 'HTML'), ('latex', 'LaTeX'), ('plaintext', 'Plain Text'), ('url', 'URL Only')], default='markdown', help_text='Primary content format for the reader to render', max_length=20)),
                ('markdown_content', models.TextField(blank=True, help_text='Markdown source. Supports GFM, math ($$…$$), fenced code blocks, tables.')),
                ('html_content', models.TextField(blank=True, help_text='Raw HTML content. Will be sanitized via DOMPurify on the frontend.')),
                ('latex_content', models.TextField(blank=True, help_text='LaTeX source for formula sheets or derivation notes.')),
                ('external_url', models.URLField(blank=True, help_text='External link (YouTube, PDF URL, article URL, etc.)', max_length=2000)),
                ('thumbnail', models.ImageField(blank=True, help_text='Optional thumbnail image for resource cards', null=True, upload_to='resource_thumbnails/')),
                ('estimated_read_minutes', models.PositiveIntegerField(default=5, help_text='Estimated reading/watching time in minutes')),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], db_index=True, default='beginner', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within the topic (lower = first)')),
                ('is_featured', models.BooleanField(default=False, help_text='Pinned/highlighted at top of the resource hub')),
                ('is_published', models.BooleanField(db_index=True, default=False, help_text='Only published resources appear on the frontend')),
                ('is_ai_generated', models.BooleanField(default=False, help_text='True if content was generated by AI')),
                ('ai_summary', models.TextField(blank=True, help_text='Short AI-generated summary shown as a callout in the article reader')),
                ('view_count', models.PositiveIntegerField(default=0, editable=False, help_text='Auto-incremented on each API read')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin/staff who created this resource', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_resources', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='resources', to='quiz.resourcetag')),
                ('topic', models.ForeignKey(help_text='The roadmap topic this resource belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='topic_resources', to='quiz.roadmaptopic')),
            ],
            options={
                'verbose_name': 'Topic Resource',
                'verbose_name_plural': 'Topic Resources',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(blank=True, max_length=100, null=True)),
                ('guest_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('score', models.FloatField()),
                ('total_questions', models.IntegerField()),
                ('correct_answers', models.IntegerField()),
                ('percentage', models.FloatField()),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('duration', models.IntegerField(blank=True, default=0, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('current_question_index', models.IntegerField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='quiz.exam')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at'],
                'indexes': [models.Index(fields=['user', 'completed_at'], name='attempt_user_date_idx')],
            },
        ),
        migrations.CreateModel(
            name='ResourceProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('last_viewed_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_progress', to=settings.AUTH_USER_MODEL)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='quiz.topicresource')),
            ],
            options={
                'verbose_name': 'Resource Progress',
                'verbose_name_plural': 'Resource Progress',
                'unique_together': {('user', 'resource')},
            },
        ),
        migrations.CreateModel(
            name='ResourceBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmarked_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_bookmarks', to=settings.AUTH_USER_MODEL)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='quiz.topicresource')),
            ],
            options={
                'verbose_name': 'Resource Bookmark',
                'verbose_name_plural': 'Resource Bookmarks',
                'ordering': ['-bookmarked_at'],
                'unique_together': {('user', 'resource')},
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_options', models.JSONField(blank=True, default=list, help_text="List of option IDs selected by user, e.g. ['A', 'B']")),
                ('text_answer', models.TextField(blank=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('is_flagged_for_review', models.BooleanField(default=False)),
                ('is_bookmarked', models.BooleanField(default=False)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='quiz.exam')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question')),
            ],
            options={
                'ordering': ['answered_at'],
                'unique_together': {('session_id', 'question')},
            },
        ),
        migrations.CreateModel(
            name='UserTopicProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('done', 'Done'), ('skip', 'Skip')], default='pending', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='quiz.roadmaptopic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'topic')},
            },
        ),
    ]
