# Generated by Django 5.2.15 on 2026-06-20 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi')], help_text='Target language', max_length=10)),
                ('question_text', models.TextField(help_text='Translated question text')),
                ('explanation', models.TextField(blank=True, help_text='Translated explanation text', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(help_text='The question being translated', on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='quiz.question')),
            ],
            options={
                'verbose_name': 'Question Translation',
                'verbose_name_plural': 'Question Translations',
                'indexes': [models.Index(fields=['question', 'language'], name='quiz_questi_questio_759495_idx')],
                'unique_together': {('question', 'language')},
            },
        ),
    ]
