# Generated by Django 4.2.7 on 2026-01-12 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_question_image_question_is_image_based'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='category',
            field=models.CharField(choices=[('ssc', 'SSC'), ('upsc', 'UPSC'), ('railways', 'Railways'), ('defence', 'Defence'), ('banking', 'Banking'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
