# Generated by Django 5.2.15 on 2026-06-20 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_questiontranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='question_images/'),
        ),
        migrations.AddField(
            model_name='question',
            name='is_image_based',
            field=models.BooleanField(default=False),
        ),
    ]
