# Generated by Django 5.2.15 on 2026-06-20 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_question_image_question_is_image_based'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='passage',
        ),
        migrations.RemoveField(
            model_name='question',
            name='ai_tutor_data',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer_metadata',
        ),
        migrations.RemoveField(
            model_name='question',
            name='cognitive_level',
        ),
        migrations.RemoveField(
            model_name='question',
            name='content_blocks',
        ),
        migrations.RemoveField(
            model_name='question',
            name='difficulty_label',
        ),
        migrations.RemoveField(
            model_name='question',
            name='difficulty_score',
        ),
        migrations.RemoveField(
            model_name='question',
            name='duplicate_hash',
        ),
        migrations.RemoveField(
            model_name='question',
            name='explanation_blocks',
        ),
        migrations.RemoveField(
            model_name='question',
            name='language',
        ),
        migrations.RemoveField(
            model_name='question',
            name='options_blocks',
        ),
        migrations.RemoveField(
            model_name='question',
            name='quality_score',
        ),
        migrations.RemoveField(
            model_name='question',
            name='subtopic',
        ),
        migrations.RemoveField(
            model_name='question',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='question',
            name='translation_group_id',
        ),
        migrations.RemoveField(
            model_name='question',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='selected_options',
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='question',
            name='question_text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('short_answer', 'Short Answer')], default='multiple_choice', max_length=20),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.question')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='useranswer',
            name='selected_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.answer'),
        ),
        migrations.CreateModel(
            name='AnswerTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi')], help_text='Target language', max_length=10)),
                ('answer_text', models.TextField(help_text='Translated answer text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answer', models.ForeignKey(help_text='The answer choice being translated', on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='quiz.answer')),
            ],
            options={
                'verbose_name': 'Answer Translation',
                'verbose_name_plural': 'Answer Translations',
                'unique_together': {('answer', 'language')},
            },
        ),
        migrations.DeleteModel(
            name='Passage',
        ),
    ]
