# Generated by Django 5.2.15 on 2026-08-10 18:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_remove_question_passage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="URL-safe identifier (e.g. 'quantitative-aptitude')", unique=True, validators=[django.core.validators.RegexValidator(message='Slug must be lowercase alphanumeric and hyphens only', regex='^[a-z0-9-]+$')])),
                ('name', models.CharField(help_text="Display name (e.g. 'Quantitative Aptitude')", max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='school', help_text='Material Symbol name', max_length=50)),
                ('order', models.IntegerField(default=0, help_text='Display order within subcategory')),
                ('is_active', models.BooleanField(default=True, help_text='Show on frontend?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='quiz.subcategory')),
            ],
            options={
                'verbose_name_plural': 'Topics',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='topic',
            field=models.ForeignKey(blank=True, help_text='Optional: Select the specific topic this exam belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='quiz.topic'),
        ),
    ]
