# Generated by Django 5.2.15 on 2026-08-15 11:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_tag_remove_answer_question_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examquestion',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='question',
            name='exams',
        ),
        migrations.RemoveField(
            model_name='questionimage',
            name='alt_text',
        ),
        migrations.RemoveField(
            model_name='questionimage',
            name='token',
        ),
        migrations.RemoveField(
            model_name='questionimage',
            name='url',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='text_answer',
        ),
        migrations.AddField(
            model_name='exam',
            name='questions',
            field=models.ManyToManyField(related_name='exams', through='quiz.ExamQuestion', to='quiz.question'),
        ),
        migrations.AddField(
            model_name='questionimage',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='question_images/'),
        ),
        migrations.AddField(
            model_name='questionimage',
            name='ocr_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='answer_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='correctionsuggestion',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='currentaffair',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='exam',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_questions', to='quiz.exam'),
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='examroadmap',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty_score',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.CharField(editable=False, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='origin',
            field=models.CharField(blank=True, help_text='e.g. ssc_cgl_2023, manual', max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(default='multiple_choice', max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, to='quiz.tag'),
        ),
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='questionpaperupload',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='topicresource',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
