# Generated by Django 4.2.7 on 2026-02-09 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_question_difficulty_question_subject_question_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['order', 'name'], 'verbose_name_plural': 'SubCategories'},
        ),
        migrations.RemoveField(
            model_name='exam',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='bg_color',
            field=models.CharField(default='bg-blue-100', help_text='Tailwind background class', max_length=50),
        ),
        migrations.AddField(
            model_name='category',
            name='icon_color',
            field=models.CharField(default='blue', help_text="Tailwind color name (e.g. 'blue', 'purple')", max_length=20),
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Show on frontend?'),
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order (lower = first)'),
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='shift',
            field=models.CharField(blank=True, help_text="e.g., 'Shift 1', 'Morning', 'Afternoon'", max_length=50),
        ),
        migrations.AddField(
            model_name='exam',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', help_text='Draft exams are not visible to students', max_length=20),
        ),
        migrations.AddField(
            model_name='exam',
            name='year',
            field=models.IntegerField(blank=True, help_text='Exam year (e.g., 2024)', null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Show on frontend?'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order within category'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(default='school', help_text='Material Symbol name', max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text="Display name (e.g. 'SSC')", max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text="URL-safe identifier (e.g. 'ssc')", unique=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive exams are hidden from students'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='subcategory',
            field=models.ForeignKey(blank=True, help_text='Select the subcategory this exam belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='quiz.subcategory'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='title',
            field=models.CharField(help_text='Exam title', max_length=200),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='icon',
            field=models.CharField(default='school', help_text='Material Symbol name', max_length=50),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(help_text="Display name (e.g. 'SSC CGL')", max_length=100),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(help_text="URL-safe identifier (e.g. 'ssc-cgl')", unique=True),
        ),
    ]
