# Generated by Django 5.2.15 on 2026-08-16 17:19

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_alter_question_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examattempt',
            options={'ordering': ['-started_at']},
        ),
        migrations.AlterModelOptions(
            name='practicesession',
            options={'ordering': ['-started_at']},
        ),
        migrations.RemoveIndex(
            model_name='examattempt',
            name='attempt_user_date_idx',
        ),
        migrations.AddField(
            model_name='examattempt',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='practicesession',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='is_correct',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['user', 'started_at'], name='attempt_user_date_idx'),
        ),
    ]
