# Generated by Django 4.2.7 on 2026-02-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='marks_per_question',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Marks awarded for each correct answer', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='total_marks',
            field=models.IntegerField(blank=True, help_text='Total marks for this exam', null=True),
        ),
    ]
