# Generated by Django 4.2.7 on 2026-05-14 19:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_correctionsuggestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentAffair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=600, unique=True)),
                ('content', models.TextField(help_text='Full summarized content from AI')),
                ('summary', models.TextField(blank=True, help_text='Short 2-sentence summary for list view')),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('source_name', models.CharField(blank=True, max_length=200)),
                ('source_url', models.URLField(blank=True, max_length=1000)),
                ('published_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.category')),
            ],
            options={
                'verbose_name_plural': 'Current Affairs',
                'ordering': ['-published_date', '-created_at'],
            },
        ),
    ]
