# Generated by Django 4.2.7 on 2026-05-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_examroadmap_roadmapphase_roadmaptopic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertopicprogress',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='roadmaptopic',
            name='resources',
            field=models.JSONField(blank=True, default=list, help_text="List of resources e.g. [{'type': 'video', 'url': '...', 'title': '...'}]"),
        ),
        migrations.AddField(
            model_name='usertopicprogress',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('done', 'Done'), ('skip', 'Skip')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='usertopicprogress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
