# Generated by Django 4.2.7 on 2026-05-17 17:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0016_remove_usertopicprogress_is_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examroadmap',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_roadmaps', to=settings.AUTH_USER_MODEL),
        ),
    ]
