# Generated by Django 4.2.7 on 2026-05-17 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_examroadmap_bookmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='ai_summary',
            field=models.TextField(blank=True, help_text='Markdown formatted AI summary', null=True),
        ),
    ]
