# Generated by Django 4.2.7 on 2026-05-20 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0018_exam_ai_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('color', models.CharField(default='gray', help_text="Tailwind color name e.g. 'blue', 'green', 'purple'", max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TopicResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated from title', max_length=550)),
                ('short_description', models.TextField(blank=True, help_text='One-line summary shown in resource cards')),
                ('resource_type', models.CharField(choices=[('article', 'Article'), ('markdown_note', 'Markdown Note'), ('html_note', 'HTML Note'), ('latex_note', 'LaTeX Note'), ('video', 'Video'), ('pdf', 'PDF'), ('external_link', 'External Link'), ('ai_note', 'AI Note'), ('formula_sheet', 'Formula Sheet'), ('quiz', 'Quiz / Practice Set')], db_index=True, default='article', help_text='What kind of content is this?', max_length=30)),
                ('content_format', models.CharField(choices=[('markdown', 'Markdown'), ('html', 'HTML'), ('latex', 'LaTeX'), ('plaintext', 'Plain Text'), ('url', 'URL Only')], default='markdown', help_text='Primary content format for the reader to render', max_length=20)),
                ('markdown_content', models.TextField(blank=True, help_text='Markdown source. Supports GFM, math ($$…$$), fenced code blocks, tables.')),
                ('html_content', models.TextField(blank=True, help_text='Raw HTML content. Will be sanitized via DOMPurify on the frontend.')),
                ('latex_content', models.TextField(blank=True, help_text='LaTeX source for formula sheets or derivation notes.')),
                ('external_url', models.URLField(blank=True, help_text='External link (YouTube, PDF URL, article URL, etc.)', max_length=2000)),
                ('thumbnail', models.ImageField(blank=True, help_text='Optional thumbnail image for resource cards', null=True, upload_to='resource_thumbnails/')),
                ('estimated_read_minutes', models.PositiveIntegerField(default=5, help_text='Estimated reading/watching time in minutes')),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], db_index=True, default='beginner', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within the topic (lower = first)')),
                ('is_featured', models.BooleanField(default=False, help_text='Pinned/highlighted at top of the resource hub')),
                ('is_published', models.BooleanField(db_index=True, default=False, help_text='Only published resources appear on the frontend')),
                ('is_ai_generated', models.BooleanField(default=False, help_text='True if content was generated by AI')),
                ('ai_summary', models.TextField(blank=True, help_text='Short AI-generated summary shown as a callout in the article reader')),
                ('view_count', models.PositiveIntegerField(default=0, editable=False, help_text='Auto-incremented on each API read')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin/staff who created this resource', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_resources', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='resources', to='quiz.resourcetag')),
                ('topic', models.ForeignKey(help_text='The roadmap topic this resource belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='topic_resources', to='quiz.roadmaptopic')),
            ],
            options={
                'verbose_name': 'Topic Resource',
                'verbose_name_plural': 'Topic Resources',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResourceProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('last_viewed_at', models.DateTimeField(auto_now=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='quiz.topicresource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resource Progress',
                'verbose_name_plural': 'Resource Progress',
                'unique_together': {('user', 'resource')},
            },
        ),
        migrations.CreateModel(
            name='ResourceBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmarked_at', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='quiz.topicresource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resource Bookmark',
                'verbose_name_plural': 'Resource Bookmarks',
                'ordering': ['-bookmarked_at'],
                'unique_together': {('user', 'resource')},
            },
        ),
    ]
