# Generated by Django 4.2.7 on 2026-05-23 08:08

from django.db import migrations, models
import django.db.models.deletion
import quiz.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0019_topicresource_cms'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='supported_languages',
            field=models.JSONField(default=quiz.models.get_default_languages, help_text='Supported languages for this exam'),
        ),
        migrations.CreateModel(
            name='QuestionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi')], help_text='Target language', max_length=10)),
                ('question_text', models.TextField(help_text='Translated question text')),
                ('explanation', models.TextField(blank=True, help_text='Translated explanation text', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(help_text='The question being translated', on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='quiz.question')),
            ],
            options={
                'verbose_name': 'Question Translation',
                'verbose_name_plural': 'Question Translations',
                'indexes': [models.Index(fields=['question', 'language'], name='quiz_questi_questio_759495_idx')],
                'unique_together': {('question', 'language')},
            },
        ),
        migrations.CreateModel(
            name='AnswerTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi')], help_text='Target language', max_length=10)),
                ('answer_text', models.TextField(help_text='Translated answer text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answer', models.ForeignKey(help_text='The answer choice being translated', on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='quiz.answer')),
            ],
            options={
                'verbose_name': 'Answer Translation',
                'verbose_name_plural': 'Answer Translations',
                'unique_together': {('answer', 'language')},
            },
        ),
    ]
