# Generated by Django 4.2.7 on 2026-05-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0021_examattempt_practicesession_useranswer_is_bookmarked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='current_question_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='current_question_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
    ]
