# Generated by Django 4.2.7 on 2026-05-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0022_examattempt_current_question_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='syllabus_pdf',
            field=models.FileField(
                blank=True,
                help_text='Syllabus PDF file for automated roadmap generation',
                null=True,
                upload_to='syllabus_pdfs/'
            ),
        ),
        migrations.AddField(
            model_name='roadmaptopic',
            name='prerequisites',
            field=models.ManyToManyField(
                blank=True,
                help_text='Prerequisites required before studying this topic',
                related_name='dependent_topics',
                to='quiz.roadmaptopic'
            ),
        ),
    ]
