# Generated by Django 4.2.7 on 2026-05-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0023_subcategory_syllabus_pdf_roadmaptopic_prerequisites'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['user', 'completed_at'], name='attempt_user_date_idx'),
        ),
    ]
