# Generated by Django 4.2.7 on 2026-05-30 11:05

from django.db import migrations

def create_fts_index(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute("""
            CREATE INDEX IF NOT EXISTS topic_resource_fts_idx 
            ON quiz_topicresource USING gin (
                (setweight(to_tsvector('english', COALESCE(title, '')), 'A') || 
                 setweight(to_tsvector('english', COALESCE(short_description, '')), 'B') || 
                 setweight(to_tsvector('english', COALESCE(ai_summary, '')), 'C') || 
                 setweight(to_tsvector('english', COALESCE(markdown_content, '')), 'D'))
            );
        """)

def drop_fts_index(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute("DROP INDEX IF EXISTS topic_resource_fts_idx;")


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0024_add_performance_indexes'),
    ]

    operations = [
        migrations.RunPython(create_fts_index, drop_fts_index),
    ]
