# Generated by Django 5.2.15 on 2026-06-13 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0025_add_fts_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionpaperupload',
            name='exam',
        ),
        migrations.AddField(
            model_name='questionpaperupload',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz.category'),
            preserve_default=False,
        ),
    ]
