# Generated by Django 5.2.15 on 2026-06-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0026_remove_questionpaperupload_exam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
