# Generated by Django 5.2.15 on 2026-06-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0027_question_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
