# Generated by Django 5.2.15 on 2026-06-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0028_alter_exam_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='negative_marks',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Marks deducted for each wrong answer', max_digits=5),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='practicesession',
            name='score',
            field=models.FloatField(),
        ),
    ]
