# Generated by Django 5.2.15 on 2026-06-15 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0029_exam_negative_marks_alter_examattempt_score_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='points',
            new_name='marks',
        ),
    ]
