# Generated by Django 4.2.7 on 2026-06-17 18:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0030_rename_points_question_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmaptopic',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Slug must be lowercase alphanumeric and hyphens only', regex='^[a-z0-9-]+$')]),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text="URL-safe identifier (e.g. 'ssc')", unique=True, validators=[django.core.validators.RegexValidator(message='Slug must be lowercase alphanumeric and hyphens only', regex='^[a-z0-9-]+$')]),
        ),
        migrations.AlterField(
            model_name='currentaffair',
            name='slug',
            field=models.SlugField(max_length=600, unique=True, validators=[django.core.validators.RegexValidator(message='Slug must be lowercase alphanumeric and hyphens only', regex='^[a-z0-9-]+$')]),
        ),
        migrations.AlterField(
            model_name='resourcetag',
            name='slug',
            field=models.SlugField(unique=True, validators=[django.core.validators.RegexValidator(message='Slug must be lowercase alphanumeric and hyphens only', regex='^[a-z0-9-]+$')]),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(help_text="URL-safe identifier (e.g. 'ssc-cgl')", unique=True, validators=[django.core.validators.RegexValidator(message='Slug must be lowercase alphanumeric and hyphens only', regex='^[a-z0-9-]+$')]),
        ),
        migrations.AlterField(
            model_name='topicresource',
            name='slug',
            field=models.SlugField(blank=True, help_text='Auto-generated from title', max_length=550, unique=True, validators=[django.core.validators.RegexValidator(message='Slug must be lowercase alphanumeric and hyphens only', regex='^[a-z0-9-]+$')]),
        ),
    ]
