# Generated by Django 5.2.15 on 2026-06-17 18:41

from django.db import migrations, models
from django.utils.text import slugify


def populate_exam_slugs(apps, schema_editor):
    """Backfill slug for existing Exam rows using subcategory slug + year + shift."""
    Exam = apps.get_registered_model('quiz', 'Exam')
    existing_slugs = set()

    for exam in Exam.objects.select_related('subcategory').all():
        parts = []
        if exam.subcategory and exam.subcategory.slug:
            parts.append(exam.subcategory.slug)
        if exam.year:
            parts.append(str(exam.year))
        if exam.shift:
            parts.append(slugify(exam.shift))

        base = '-'.join(parts) if parts else f'exam-{exam.pk}'
        slug = base
        n = 1
        while slug in existing_slugs:
            slug = f'{base}-{n}'
            n += 1

        existing_slugs.add(slug)
        exam.slug = slug
        exam.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0031_roadmaptopic_slug_alter_category_slug_and_more'),
    ]

    operations = [
        # First add the field as nullable (allows existing rows to have NULL temporarily)
        migrations.AddField(
            model_name='exam',
            name='slug',
            field=models.SlugField(
                blank=True,
                null=True,
                help_text='Auto-generated from subcategory + year + shift. Override only if needed.',
                max_length=250,
                unique=True,
            ),
        ),
        # Populate slugs for all existing rows
        migrations.RunPython(populate_exam_slugs, migrations.RunPython.noop),
        # Now make it non-nullable (all rows have slugs now)
        migrations.AlterField(
            model_name='exam',
            name='slug',
            field=models.SlugField(
                blank=True,
                help_text='Auto-generated from subcategory + year + shift. Override only if needed.',
                max_length=250,
                unique=True,
            ),
        ),
    ]
