# Generated by Django 4.2.7 on 2026-05-27 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(db_index=True, help_text='Registered job type key, e.g. "ai.explain", "ai.parse_pdf", "community.recalculate_ranks".', max_length=255)),
                ('priority', models.IntegerField(choices=[(10, 'Low'), (20, 'Normal'), (30, 'High'), (40, 'Critical')], default=20, help_text='Job priority.  Higher value = more urgent.')),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('FAILED', 'Failed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='QUEUED', max_length=20)),
                ('stage', models.CharField(blank=True, default='', help_text='Current named stage, e.g. "parsing", "generating".', max_length=255)),
                ('progress', models.IntegerField(default=0, help_text='Completion percentage, 0–100.')),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Immutable input data, set at creation.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Mutable runtime annotations (e.g. worker hostname).')),
                ('result', models.JSONField(blank=True, help_text='Output data, populated on completion.', null=True)),
                ('error', models.TextField(blank=True, default='', help_text='Error message and traceback on failure.')),
                ('retries', models.IntegerField(default=0, help_text='Number of retry attempts executed so far.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, help_text='User who initiated the job.  NULL for system jobs.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='background_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Background Job',
                'verbose_name_plural': 'Background Jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'priority'], name='jobs_status_priority_idx'), models.Index(fields=['type', 'status'], name='jobs_type_status_idx'), models.Index(fields=['user', 'status'], name='jobs_user_status_idx'), models.Index(fields=['status', 'created_at'], name='jobs_status_created_idx')],
            },
        ),
    ]
