# Generated by Django 5.2.15 on 2026-06-20 09:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True, validators=[django.core.validators.RegexValidator(message='Slug must be lowercase alphanumeric and hyphens only', regex='^[a-z0-9-]+$')])),
                ('description', models.CharField(max_length=300)),
                ('icon', models.CharField(default='sparkles', max_length=50)),
                ('color_gradient', models.CharField(default='from-amber-400 to-orange-500', max_length=100)),
                ('criteria_type', models.CharField(choices=[('solutions_count', 'Solutions Count'), ('xp_threshold', 'XP Threshold'), ('streak', 'Streak Days'), ('uploads', 'Uploads Approved'), ('suggestions', 'Suggestions Approved'), ('upvotes', 'Upvotes Received'), ('ai_verified', 'AI Verified Count'), ('manual', 'Manual Award')], default='manual', max_length=30)),
                ('criteria_value', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('REPLY', 'Reply to comment'), ('UPVOTE', 'Solution upvoted'), ('REWARD', 'XP Reward'), ('BADGE', 'Badge Earned'), ('SYSTEM', 'System notification')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_char', models.CharField(blank=True, max_length=1)),
                ('avatar_image', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('bio', models.TextField(blank=True)),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('show_profile_pic', models.BooleanField(default=True)),
                ('xp', models.IntegerField(default=0)),
                ('streak', models.IntegerField(default=0)),
                ('best_streak', models.IntegerField(default=0)),
                ('last_activity', models.DateField(blank=True, null=True)),
                ('total_solutions', models.IntegerField(default=0)),
                ('total_comments', models.IntegerField(default=0)),
                ('total_upvotes_received', models.IntegerField(default=0)),
                ('total_views', models.IntegerField(default=0)),
                ('uploads_approved', models.IntegerField(default=0)),
                ('suggestions_approved', models.IntegerField(default=0)),
                ('ai_verified_count', models.IntegerField(default=0)),
                ('reputation_score', models.FloatField(default=0.0)),
                ('community_rank', models.IntegerField(default=0)),
                ('percentile', models.FloatField(default=0.0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('upvotes', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('ai_score', models.FloatField(blank=True, null=True)),
                ('ai_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_solutions', to='quiz.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('upvotes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='community.comment')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community_comments', to='quiz.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('solution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='community.solution')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SolutionUpvote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upvote_records', to='community.solution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution_upvotes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_badges', to='community.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-awarded_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('bi', 'Bilingual')], default='en', max_length=10)),
                ('daily_study_goal', models.IntegerField(default=60)),
                ('notify_exam_results', models.BooleanField(default=True)),
                ('notify_roadmap_updates', models.BooleanField(default=True)),
                ('notify_contributor_activity', models.BooleanField(default=True)),
                ('notify_weekly_report', models.BooleanField(default=True)),
                ('notify_new_resources', models.BooleanField(default=True)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='system', max_length=10)),
                ('is_public_profile', models.BooleanField(default=True)),
                ('show_xp', models.BooleanField(default=True)),
                ('show_streak', models.BooleanField(default=True)),
                ('show_rank', models.BooleanField(default=True)),
                ('show_contribution_activity', models.BooleanField(default=True)),
                ('primary_exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='quiz.subcategory')),
                ('secondary_exams', models.ManyToManyField(blank=True, to='quiz.subcategory')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommentUpvote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upvote_records', to='community.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_upvotes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['comment', 'user'], name='community_c_comment_ec0d30_idx')],
                'unique_together': {('comment', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ContributorActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('SOLUTION', 'Solution Posted'), ('COMMENT', 'Comment Posted'), ('UPLOAD', 'Paper Uploaded'), ('SUGGESTION', 'Correction Suggested'), ('EXAM', 'Exam Completed'), ('STREAK', 'Streak Milestone'), ('BADGE', 'Badge Earned'), ('ROADMAP', 'Roadmap Topic Done')], max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='activity_user_date_idx'), models.Index(fields=['created_at'], name='activity_date_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='solution',
            index=models.Index(fields=['question', 'created_at'], name='solution_question_date_idx'),
        ),
        migrations.AddIndex(
            model_name='solution',
            index=models.Index(fields=['user', 'created_at'], name='solution_author_date_idx'),
        ),
        migrations.AddIndex(
            model_name='solutionupvote',
            index=models.Index(fields=['solution', 'user'], name='community_s_solutio_f9892f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='solutionupvote',
            unique_together={('solution', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='userbadge',
            unique_together={('user', 'badge')},
        ),
    ]
