# Generated by Django 4.2.7 on 2026-05-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_badge_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contributoractivity',
            index=models.Index(fields=['user', 'created_at'], name='activity_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='contributoractivity',
            index=models.Index(fields=['created_at'], name='activity_date_idx'),
        ),
        migrations.AddIndex(
            model_name='solution',
            index=models.Index(fields=['question', 'created_at'], name='solution_question_date_idx'),
        ),
        migrations.AddIndex(
            model_name='solution',
            index=models.Index(fields=['user', 'created_at'], name='solution_author_date_idx'),
        ),
    ]
