# Generated by Django 4.2.7 on 2026-06-04 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0025_add_fts_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0005_add_solution_upvote_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('bi', 'Bilingual')], default='en', max_length=10)),
                ('daily_study_goal', models.IntegerField(default=60)),
                ('notify_exam_results', models.BooleanField(default=True)),
                ('notify_roadmap_updates', models.BooleanField(default=True)),
                ('notify_contributor_activity', models.BooleanField(default=True)),
                ('notify_weekly_report', models.BooleanField(default=True)),
                ('notify_new_resources', models.BooleanField(default=True)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='system', max_length=10)),
                ('is_public_profile', models.BooleanField(default=True)),
                ('show_xp', models.BooleanField(default=True)),
                ('show_streak', models.BooleanField(default=True)),
                ('show_rank', models.BooleanField(default=True)),
                ('show_contribution_activity', models.BooleanField(default=True)),
                ('primary_exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='quiz.subcategory')),
                ('secondary_exams', models.ManyToManyField(blank=True, to='quiz.subcategory')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
