# Generated by Django 4.2.7 on 2026-06-17 18:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_commentupvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='slug',
            field=models.SlugField(unique=True, validators=[django.core.validators.RegexValidator(message='Slug must be lowercase alphanumeric and hyphens only', regex='^[a-z0-9-]+$')]),
        ),
    ]
